import Component from "ember-component";
import styles from '../../styles/components/ui-icon-page/index';
import set from "ember-metal/set";
import Clipboard from "clipboard";

export default Component.extend({
  icon: [
    {icon: 'arrows-16px-1_cloud-download-95',},
    {icon: 'arrows-16px-1_cloud-upload-96',},
    {icon: 'arrows-16px-1_curved-next',},
    {icon: 'arrows-16px-1_curved-previous',},
    {icon: 'arrows-16px-1_direction-53',},
    {icon: 'arrows-16px-1_double-left',},
    {icon: 'arrows-16px-1_double-right',},
    {icon: 'arrows-16px-1_download',},
    {icon: 'arrows-16px-1_enlarge-diagonal-43',},
    {icon: 'arrows-16px-1_enlarge-diagonal-44',},
    {icon: 'arrows-16px-1_enlarge-horizontal',},
    {icon: 'arrows-16px-1_enlarge-vertical',},
    {icon: 'arrows-16px-1_fullscreen-double-74',},
    {icon: 'arrows-16px-1_fullscreen-double-75',},
    {icon: 'arrows-16px-1_minimal-down',},
    {icon: 'arrows-16px-1_minimal-left',},
    {icon: 'arrows-16px-1_minimal-right',},
    {icon: 'arrows-16px-1_minimal-up',},
    {icon: 'arrows-16px-1_refresh-68',},
    {icon: 'arrows-16px-1_share-91',},
    {icon: 'arrows-16px-1_small-triangle-down',},
    {icon: 'arrows-16px-1_small-triangle-left',},
    {icon: 'arrows-16px-1_small-triangle-right',},
    {icon: 'arrows-16px-1_small-triangle-up',},
    {icon: 'arrows-16px-1_tail-down',},
    {icon: 'arrows-16px-1_tail-left',},
    {icon: 'arrows-16px-1_tail-right',},
    {icon: 'arrows-16px-1_tail-triangle-down',},
    {icon: 'arrows-16px-1_tail-triangle-left',},
    {icon: 'arrows-16px-1_tail-triangle-right',},
    {icon: 'arrows-16px-1_tail-triangle-up',},
    {icon: 'arrows-16px-1_tail-up',},
    {icon: 'arrows-16px-2_select-83',},
    {icon: 'arrows-16px-2_select-84',},
    {icon: 'arrows-16px-2_small-left',},
    {icon: 'arrows-16px-2_small-right',},
    {icon: 'arrows-16px-2_square-download',},
    {icon: 'arrows-16px-2_square-upload',},
    {icon: 'arrows-16px-3_small-down',},
    {icon: 'arrows-16px-3_small-up',},
    {icon: 'arrows-16px-4_enlarge-46',},
    {icon: 'arrows-16px-4_input-12',},
    {icon: 'arrows-16px-4_launch-11',},
    {icon: 'arrows-16px-4_logout',},
    {icon: 'shopping-16px_cart-modern',},
    {icon: 'shopping-16px_cart-modern-in',},
    {icon: 'shopping-16px_gift',},
    {icon: 'shopping-16px_tag',},
    {icon: 'shopping-16px_tag-content',},
    {icon: 'ui-16px-1_bell-53',},
    {icon: 'ui-16px-1_bold-add',},
    {icon: 'ui-16px-1_bold-delete',},
    {icon: 'ui-16px-1_bold-remove',},
    {icon: 'ui-16px-1_calendar-60',},
    {icon: 'ui-16px-1_check',},
    {icon: 'ui-16px-1_check-bold',},
    {icon: 'ui-16px-1_check-curve',},
    {icon: 'ui-16px-1_check-simple',},
    {icon: 'ui-16px-1_check-small',},
    {icon: 'ui-16px-1_email-83',},
    {icon: 'ui-16px-1_email-84',},
    {icon: 'ui-16px-1_home-minimal',},
    {icon: 'ui-16px-1_home-simple',},
    {icon: 'ui-16px-1_lock',},
    {icon: 'ui-16px-1_notification-69',},
    {icon: 'ui-16px-1_pencil',},
    {icon: 'ui-16px-1_preferences',},
    {icon: 'ui-16px-1_preferences-rotate',},
    {icon: 'ui-16px-1_settings-gear-63',},
    {icon: 'ui-16px-1_simple-add',},
    {icon: 'ui-16px-1_simple-delete',},
    {icon: 'ui-16px-1_simple-remove',},
    {icon: 'ui-16px-1_trash',},
    {icon: 'ui-16px-1_trash-simple',},
    {icon: 'ui-16px-1_zoom',},
    {icon: 'ui-16px-1_zoom-in',},
    {icon: 'ui-16px-1_zoom-out',},
    {icon: 'ui-16px-2_alert-circle-!',},
    {icon: 'ui-16px-2_alert-circle-?',},
    {icon: 'ui-16px-2_alert-circle-i',},
    {icon: 'ui-16px-2_alert-square-?',},
    {icon: 'ui-16px-2_ban',},
    {icon: 'ui-16px-2_chat',},
    {icon: 'ui-16px-2_chat-content',},
    {icon: 'ui-16px-2_chat-round',},
    {icon: 'ui-16px-2_chat-round-content',},
    {icon: 'ui-16px-2_cloud-25',},
    {icon: 'ui-16px-2_favourite-31',},
    {icon: 'ui-16px-2_filter',},
    {icon: 'ui-16px-2_fullsize',},
    {icon: 'ui-16px-2_grid-45',},
    {icon: 'ui-16px-2_grid-46',},
    {icon: 'ui-16px-2_grid-48',},
    {icon: 'ui-16px-2_grid-50',},
    {icon: 'ui-16px-2_grid-square',},
    {icon: 'ui-16px-2_link-66',},
    {icon: 'ui-16px-2_link-68',},
    {icon: 'ui-16px-2_link-69',},
    {icon: 'ui-16px-2_menu-dots',},
    {icon: 'ui-16px-2_share',},
    {icon: 'ui-16px-2_share-bold',},
    {icon: 'ui-16px-2_small-add',},
    {icon: 'ui-16px-2_small-delete',},
    {icon: 'ui-16px-2_small-remove',},
    {icon: 'ui-16px-2_time',},
    {icon: 'ui-16px-2_time-clock',},
    {icon: 'ui-16px-2_time-countdown',},
    {icon: 'ui-16px-3_alert',},
    {icon: 'ui-16px-3_card-alert',},
    {icon: 'ui-16px-3_chat-45',},
    {icon: 'ui-16px-3_chat-46',},
    {icon: 'ui-16px-3_heart',},
    {icon: 'ui-16px-3_infinite',},
    {icon: 'ui-16px-3_phone',},
    {icon: 'ui-16px-3_signal',},
    {icon: 'ui-16px-e_round-e-alert',},
    {icon: 'ui-16px-e_round-e-help',},
    {icon: 'ui-16px-e_round-e-info',},
    {icon: 'ui-16px-e_square-e-alert',},
    {icon: 'ui-16px-e_square-e-help',},
    {icon: 'ui-16px-e_square-e-info',},
    {icon: 'ui-16px-e_star-empty',},
    {icon: 'users-16px-2_a-add',},
    {icon: 'users-16px-2_a-check',},
    {icon: 'users-16px-2_a-edit',},
    {icon: 'users-16px-2_a-heart',},
    {icon: 'users-16px-2_a-remove',},
    {icon: 'users-16px-2_multiple',},
    {icon: 'users-16px_circle-08',},
    {icon: 'users-16px_single-body',},
    {icon: 'ui-16px-2_menu-34',},
    {icon: 'tag-point',},
    {icon: 'media-16px-1_camera-19',},
    {icon: 'social-16px_logo-fb-simple',},
    {icon: 'social-16px_logo-google-plus',},
    {icon: 'social-16px_logo-twitter',},
  ],

  mouseMove({target}) {
    if (target.classList.contains(styles['svg-container'])) {
      const text = target.querySelector('use').getAttribute('xlink:href').replace('#', '')
      set(this, 'hrefText', text)
    }
  },

  didInsertElement() {
    const icons = this.element.querySelectorAll(`.${styles['svg-container']}`)

    this.clipboard = new Clipboard(icons, {
      text(trigger) {
        return trigger.querySelector('use').getAttribute('xlink:href').replace('#', '')
      }
    })
  },

  willDestroy() {
    this.clipboard && this.clipboard.destroy()
  }
});
